### ISSUE TITLE
Stop location updates when app goes to background

### ISSUE THREAD

**Issue by joseAugustoCR** [david-serrano/locationprovider#2]
The library seems to keep getting location updates after the app goes to background and the location icon is always displayed in the status bar

How can I stop the location updates in onStop method of the activity and request again in onResume?

![screenshot_20181102-091826 1](https://user-images.githubusercontent.com/9751521/47915242-015fc080-de81-11e8-915a-87b38d7a055e.png)

**Comment by david-serrano** [comment]
Hi @joseAugustoCR, please update to the latest version (1.2). I have added lifecycle awareness for onPause and onResume. You can see how to integrate into the activity lifecycle in the sample app :)
